#!/bin/sh

set -eux

ROOTFS="$(mktemp -d)"

create_manifest() {
    ./security-manifest --cleanup --rootfs "$ROOTFS" -- --release ubuntu-24.04 "$@"
}

cleanup() {
    rm -f "dpkg.query"
}
trap cleanup EXIT

check_package() {
    local package="$1"
    local match="$2"
    grep "$package" dpkg.query | grep -Pz $match
}

create_manifest libc6_libs
check_package "libc6" ",libc6,2.39-0ubuntu8.4,glibc,"

create_manifest openssl_bins
check_package "openssl" ",openssl,3.0.13-0ubuntu3.5,openssl,3.0.13-0ubuntu3.5"