name: Build External Rock 


on:
    push:
        paths:
            - .github/workflows/Build_External_Rock.yaml
    workflow_dispatch:

jobs:
    build:
        uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@ROCKS-1452/oci-factory-refactor-build-rock-to-be-externally-reusable
        with:
            oci-archive-name: "external_mock-rock"
            # rock-repo: clay-lake/mock-rock
            rock-repo: https://git.savannah.gnu.org/git/screen.git
            # rock-repo-commit: main
            rock-repo-commit: master
            rockfile-directory: /mock-rock/1.1/

