name: Build External Rock

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "chiselled-python"
      rock-repo: canonical/chiselled-python
      rock-repo-commit: e0943bf2923ef50c9117ac58cd02a86146ece1fb
      rockfile-directory: python3.12/
