name: Build and Test EICAR Rock

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "eicar-rock"
      rock-repo: canonical/rocks-toolbox
      rock-repo-commit: rework_oci-factory_workflow_docs
      rockfile-directory: eicar_rock/1.0/

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: [build]
    with:
      oci-archive-name: "eicar-rock"
      test-black-box: true
      test-efficiency: true
      test-malware: true
      test-oci-compliance: true
      test-vulnerabilities: true

  end:
    # we expect malware scan to fail, so we add a final job so PR checks pass.
    if: ${{ !cancelled() }}
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo Workflow complete!
