name: Build External Rock 


on:
    push:
        paths:
            - .github/workflows/Build_External_Rock.yaml
    workflow_dispatch:

jobs:
    build:
        uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@ROCKS-1452/oci-factory-refactor-build-rock-to-be-externally-reusable
        with:
            oci-archive-name: "external_mock-rock"
            rock-repo: canonical/rocks-toolbox
            rock-repo-commit: main
            rockfile-directory: mock_rock/1.0

