name: Build External Rock


on:
    push:
        paths:
            - .github/workflows/Build_External_Rock.yaml
    workflow_dispatch:

jobs:
    build:
        # uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@ROCKS-1452/oci-factory-refactor-build-rock-to-be-externally-reusable
        uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@dc7b5339bf56afd78cc8a1193728c71c5c3d5277
        with:
            oci-archive-name: "external_mock-rock"
            rock-repo: clay-lake/mock-rock
            rock-repo-commit: main
            rockfile-directory: /mock-rock/1.1/
