name: Notify on PR close

on:
  pull_request:
    types: [closed]

jobs:
  release-reminder:
    name: Remind to release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'To create a release, please trigger the release workflow: https://github.com/canonical/rocks-toolbox/actions/workflows/release.yml'
            })
