name: Tests

on:
  push:

jobs:
  test-rockcraft-lpci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install -r rockcraft_lpci_build/requirements.test.txt
      - run: pytest rockcraft_lpci_build/tests/ -vvv -s -rP --log-cli-level=INFO

  chisel-wrapper:
    name: Chisel wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Chisel
        env:
          version: v1.1.0
        run: |
          wget "https://github.com/canonical/chisel/releases/download/${{ env.version }}/chisel_${{ env.version }}_linux_amd64.tar.gz"
          tar zxvf "chisel_${{ env.version }}_linux_amd64.tar.gz"
          sudo mv chisel /usr/local/bin/
      - name: Test chisel-wrapper
        run: |
          install() {
            ./chisel-wrapper --generate-dpkg-status status -- \
              --release ubuntu-20.04 --root "$(mktemp -d)" \
              "$@"
          }

          cleanup() {
            rm -f status
          }
          trap cleanup EXIT

          test ! -f status

          install openssl_bins
          grep "^Package:.*$" status | wc -l | grep -q "3"            # must be 3 packages

          install base-files_base
          grep "^Package:.*$" status | wc -l | grep -q "4"            # must be 4 packages
          grep "^Package:.*$" status | tail -1 | grep -q "base-files" # must be last entry

          install libc6_libs
          grep "^Package:.*$" status | wc -l | grep -q "4"            # must be 4 packages
          grep "^Package:.*$" status | tail -1 | grep -q "libc6"      # must be last entry
