name: Tag and Release

on:
  push:

jobs:
  test-rockcraft-lpci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install pytest
      - run: pytest rockcraft_lpci_build/tests/ -vvv -s -rP --log-cli-level=INF