name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-rockcraft-lpci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install -r rockcraft_lpci_build/requirements.test.txt
      - run: pytest rockcraft_lpci_build/tests/ -vvv -s -rP --log-cli-level=INFO

  chisel-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Install chisel
        run: go install github.com/canonical/chisel/cmd/chisel@latest
      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
          sudo sh -s -- -b /usr/local/bin
      - name: Test chisel-wrapper
        run: ./tests/chisel-wrapper/runtest

  chisel-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Test chisel-tools
        run: cd chisel-tools && go test ./...
